<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ItBudgetingV3.Domain\ItBudgetingV3.Domain.csproj" />
    <ProjectReference Include="..\ItBudgetingV3.Application\ItBudgetingV3.Application.csproj" />
    <ProjectReference Include="..\ItBudgetingV3.Infrastructure\ItBudgetingV3.Infrastructure.csproj" />
  </ItemGroup>

</Project>
